apiVersion: v1
kind: Service
metadata:
  name: rlaas-server
  namespace: rlaas
  labels:
    app.kubernetes.io/name: rlaas
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rlaas
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
